T=TETRIS.COM
O=TETRIS.OBJ RAND.OBJ KEYBRD.OBJ VID.OBJ PIECE.OBJ

$T: $O
  TLINK/t $**

.ASM.OBJ:
  TASM/l/t $**

TETRIS.OBJ: TETRIS.ASM COMMON.INC
RAND.OBJ: RAND.ASM COMMON.INC
KEYBRD.OBJ: KEYBRD.ASM COMMON.INC
VID.OBJ: VID.ASM COMMON.INC

RUN: $T
  $T

CLEAN:
  DEL *.OBJ
  DEL $T
